"""Agregar modelo de Comentario

Revision ID: 6d1d02cb28e6
Revises: 
Create Date: 2025-06-13 14:28:17.589012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d1d02cb28e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'comentario',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(length=200), nullable=False),
        sa.Column('contenido', sa.String(length=500), nullable=False),
        sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
        sa.Column('actividad_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['actividad_id'], ['tarea2.actividad.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='tarea2'
    )

#def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('actividad', schema=None) as batch_op:
    #    batch_op.drop_index(batch_op.f('fk_actividad_comuna1_idx'))
    #    batch_op.drop_constraint(batch_op.f('fk_actividad_comuna1'), type_='foreignkey')
    #    batch_op.create_foreign_key(None, 'comuna', ['comuna_id'], ['id'], referent_schema='tarea2')

    #with op.batch_alter_table('actividad_tema', schema=None) as batch_op:
    #    batch_op.drop_index(batch_op.f('fk_actividad_tema_actividad1_idx'))
    #    batch_op.drop_constraint(batch_op.f('fk_actividad_tema_actividad1'), type_='foreignkey')
    #    batch_op.create_foreign_key(None, 'actividad', ['actividad_id'], ['id'], referent_schema='tarea2')

    #with op.batch_alter_table('comentario', schema=None) as batch_op:
    #    batch_op.add_column(sa.Column('contenido', sa.String(length=500), nullable=False))
    #    batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=False))
    #    batch_op.alter_column('nombre',
    #           existing_type=mysql.VARCHAR(length=80),
    #           type_=sa.String(length=200),
    #           existing_nullable=False)
    #    batch_op.drop_index(batch_op.f('fk_comentario_actividad1_idx'))
    #    batch_op.drop_constraint(batch_op.f('fk_comentario_actividad1'), type_='foreignkey')
    #    batch_op.create_foreign_key(None, 'actividad', ['actividad_id'], ['id'], referent_schema='tarea2')
    #    batch_op.drop_column('fecha')
    #    batch_op.drop_column('texto')

    #with op.batch_alter_table('comuna', schema=None) as batch_op:
    #    batch_op.drop_index(batch_op.f('fk_comuna_region1_idx'))
    #    batch_op.drop_constraint(batch_op.f('fk_comuna_region1'), type_='foreignkey')
    #    batch_op.create_foreign_key(None, 'region', ['region_id'], ['id'], referent_schema='tarea2')

    #with op.batch_alter_table('contactar_por', schema=None) as batch_op:
    #    batch_op.alter_column('nombre',
    #           existing_type=mysql.ENUM('whatsapp', 'telegram', 'X', 'instagram', 'tiktok', 'otra'),
    #           type_=sa.Enum('whatsapp', 'telegram', 'instagram', 'tiktok', 'x', 'otra'),
    #           existing_nullable=False)
    #    batch_op.drop_index(batch_op.f('fk_contactar_por_actividad1_idx'))
    #    batch_op.drop_constraint(batch_op.f('fk_contactar_por_actividad1'), type_='foreignkey')
    #    batch_op.create_foreign_key(None, 'actividad', ['actividad_id'], ['id'], referent_schema='tarea2')

    #with op.batch_alter_table('foto', schema=None) as batch_op:
    #    batch_op.drop_index(batch_op.f('fk_foto_actividad1_idx'))
    #    batch_op.drop_constraint(batch_op.f('fk_foto_actividad1'), type_='foreignkey')
    #    batch_op.create_foreign_key(None, 'actividad', ['actividad_id'], ['id'], referent_schema='tarea2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_foto_actividad1'), 'actividad', ['actividad_id'], ['id'])
        batch_op.create_index(batch_op.f('fk_foto_actividad1_idx'), ['actividad_id'], unique=False)

    with op.batch_alter_table('contactar_por', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_contactar_por_actividad1'), 'actividad', ['actividad_id'], ['id'])
        batch_op.create_index(batch_op.f('fk_contactar_por_actividad1_idx'), ['actividad_id'], unique=False)
        batch_op.alter_column('nombre',
               existing_type=sa.Enum('whatsapp', 'telegram', 'instagram', 'tiktok', 'x', 'otra'),
               type_=mysql.ENUM('whatsapp', 'telegram', 'X', 'instagram', 'tiktok', 'otra'),
               existing_nullable=False)

    with op.batch_alter_table('comuna', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comuna_region1'), 'region', ['region_id'], ['id'])
        batch_op.create_index(batch_op.f('fk_comuna_region1_idx'), ['region_id'], unique=False)

    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('texto', mysql.VARCHAR(length=300), nullable=False))
        batch_op.add_column(sa.Column('fecha', mysql.TIMESTAMP(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comentario_actividad1'), 'actividad', ['actividad_id'], ['id'])
        batch_op.create_index(batch_op.f('fk_comentario_actividad1_idx'), ['actividad_id'], unique=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('contenido')

    with op.batch_alter_table('actividad_tema', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_actividad_tema_actividad1'), 'actividad', ['actividad_id'], ['id'])
        batch_op.create_index(batch_op.f('fk_actividad_tema_actividad1_idx'), ['actividad_id'], unique=False)

    with op.batch_alter_table('actividad', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_actividad_comuna1'), 'comuna', ['comuna_id'], ['id'])
        batch_op.create_index(batch_op.f('fk_actividad_comuna1_idx'), ['comuna_id'], unique=False)

    # ### end Alembic commands ###
